name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -a
      - name: Checkout
        uses: actions/checkout@v3
      - name: List Files after Checkout
        run: |
          pwd
          ls -a
      - name: Simple JS Actions
        id: greet
        uses: actions/hello-world-javascript-action@main
        with: 
          who-to-greet: Karla
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
        