name: Defining Matrix During Workflow

on: 
  workflow_dispatch:
    inputs:
      test_group:
        description: 'Which test groups do you want to run?'
        required: true
        type: string
        default: "[\"A\", \"B\", \"C\", \"D\"]"
  push:
    # branches:
      # - main
  schedule:
    - cron: "0 09 * * *"

env: 
  ALL_TEST_GROUPS: "[\"A\", \"B\", \"C\", \"D\"]"
    
jobs:
  first-job:

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    runs-on: ubuntu-latest

    steps:
      # - name: Define Test Matrix (workflow_dispatch)
      #   id: set-matrix
      #   if: ${{ github.event_name == 'workflow_dispatch' }}
      #   # run: echo "test-group=${{ inputs.test-group }}" >> "$GITHUB_OUTPUT"
      #   env: 
      #     TEST_GROUP: ${{ inputs.test_group }}
      #   run: |
      #     echo ${{fromJson(env.TEST_GROUP)}}
      #     # echo "matrix=${{ inputs.test-group }}" >> "$GITHUB_OUTPUT"


      - name: Define Test Matrix (workflow_dispatch)
        id: set-matrix
        run: | 
          if [[ ${{ github.event_name}} == "workflow_dispatch" ]]; then
            echo "matrix='${{ inputs.test_group }}'" >> $GITHUB_OUTPUT
          else
            echo "matrix='${{ env.ALL_TEST_GROUPS }}'" >> $GITHUB_OUTPUT
          fi
      - name: Print output
        run: |
          echo 'hellooooo'
          echo ${{ steps.set-matrix.outputs.matrix }}
          echo 'end'
      - name: Dump steps context
        env:
          STEPS_CONTEXT: '${{ toJSON(steps) }}'
        run: echo "$STEPS_CONTEXT"

  second-job:

    needs: first-job
    runs-on: ubuntu-latest

    # env: 
    #   MATRIX: ${{ fromJson (needs.first-job.outputs.matrix || env.TEST_GROUP) }}

    strategy:
      matrix:
        # test-group: ${{ inputs.test-group }}
        test-group: ${{ needs.first-job.outputs.matrix }}
        # test-group: [A, B, C]
      fail-fast: true
      

    steps:
      - name: List current env.TEST_GROUP
        run: echo ${{ matrix.test-group }}

      # - name: Checkout
      #   uses: actions/checkout@v3
      # - name: List Files after checkout
      #   run: |
      #     pwd
      #     ls -a
      # - name: Push a random file
      #   env: 
      #     CURRENT_TEST_GROUP: ${{ matrix.test-group }}
      #   run: | 
      #     echo $CURRENT_TEST_GROUP >> files/$CURRENT_TEST_GROUP.txt
      # - name: Publish Artifacts
      #   if: always()
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: results
      #     path: files
      #     retention-days: 2