name: Reusable Workflow

on: 
  push:
  workflow_call:
    # inputs:
    #   test-group:
    #     required: true
    #     type: string
    
jobs:
  first-job:

    strategy:
      matrix:
        # test-group: ${{ inputs.test-group }}
        test-group: [A, B, C]
      fail-fast: true
    runs-on: ubuntu-latest

    env: 
      TEST_GROUP: ${{ matrix.test-group }}

    steps:
      - name: Print something to the console
        run: | 
          echo 'Helloooo'
          echo $TEST_GROUP
      - name: Push a random file
        run: | 
          echo $TEST_GROUP >> files/$TEST_GROUP.txt
      - name: Publish Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: files
          retention-days: 2