name: Reusable Workflow

on: 
  # push:
  workflow_call:
    inputs:
      test-group:
        required: true
        default: '["A", "B", "C", "D"]'
        type: string

env: 
  TEST_GROUP: ${{ inputs.test-group }}
    
jobs:
  first-job:

    strategy:
      matrix:
        # test-group: ${{ inputs.test-group }}
        test-group: ${{ fromJSON(env.TEST_GROUP)}}
        # test-group: [A, B, C]
      fail-fast: true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: List Files after checkout
        run: |
          pwd
          ls -a
      - name: Push a random file
        env: 
          CURRENT_TEST_GROUP: ${{ matrix.test-group }}
        run: | 
          echo $CURRENT_TEST_GROUP >> files/$CURRENT_TEST_GROUP.txt
      - name: Publish Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: files
          retention-days: 2